### PR TITLE
Enable compatibility with TEE Internal Core API v1.1

### PR DESCRIPTION
**Pull request by jenswi-linaro**
While the TEE Internal Core API in OP-TEE OS is updated, enable compatibility with the last support version. This is done by by adding CFG_TA_OPTEE_CORE_API_COMPAT_1_1==y in the TA makefile.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Review by etienne-lms — COMMENTED** [review]
I seems to me that TA cannot use another value for `CFG_TA_OPTEE_CORE_API_COMPAT_1_1` than the one used to generate the devkit. Do I miss something or should devkit check `CFG_TA_OPTEE_CORE_API_COMPAT_1_1` value set for TA build does match the config set when generating libutee binaries?

**Comment by jenswi-linaro** [comment]
`CFG_TA_OPTEE_CORE_API_COMPAT_1_1` only affects how the TA uses the API, the devkit is always the same.

**Comment by jenswi-linaro** [comment]
Can we merge this?

**Pull request merged**
