### PR TITLE
OTE for Op-Tee Examples

### PR DESCRIPTION
**Pull request by etienne-lms**
Prefix all optee examples "ote_".

### CODE REVIEW

**Comment by jforissier** [comment]
Ah, ignore my comment. I just noticed the title of this PR ;)
I don't like it very much, though.

**Comment by jbech-linaro** [comment]
> I don't like it very much, though.

I do, but that is not strange, since I think I proposed it in a code review. I have no strong opinion for `ote_`, something else would also work. But I would like to avoid long prefix like `tee_example_`, `optee_example`. Since I'm happy with this you at least get my RB :)

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
What's wrong with long prefixes?  We have no hard limit, and shells do have auto-completion. `optee_example_` would be self-explanatory at least.

**Comment by etienne-lms** [comment]
I have no stong option on the choice.  I prefer optee_ than ote_. What ever let's vote and adopt one.
Proposals: ote_ ?   optee_ ?    opteex_  ?

**Comment by jbech-linaro** [comment]
> What's wrong with long prefixes?

I guess it is personal preference and yes, autocomplete works fine both in shell and in the editor, but this is about readability. For me in general, I think it is harder to read when you have long stuff (I guess I'm scarred since a previous job, where we had names where it wasn't uncommon to have a ~30 character prefix, totally stupid and totally unreadable).

> What ever let's vote and adopt one.

We don't have to vote, Jerome as maintainer has the freedom to choose whatever he prefer :)

**Comment by etienne-lms** [comment]
So Jerome, what will you dictate for this ? :) `optee_example_`

`optee_example_hello_world`
`optee_example_random`
`optee_example_aes`   (https://github.com/linaro-swg/optee_examples/pull/3)
`optee_example_secure_storage` (https://github.com/linaro-swg/optee_examples/pull/5)

**Comment by jforissier** [comment]
@etienne-lms yes please

**Comment by etienne-lms** [comment]
Ok.

**Comment by etienne-lms** [comment]
Proposal based on `optee_example_` prefixing.

**Comment by jbech-linaro** [comment]
And feel free to still use my RB :)

**Comment by jforissier** [comment]
LGTM, although I personally would not have added the prefix to the defines (UUID, CMD) and include files. It is not really needed (no ambiguity, no name conflict). And it *does* make the code less readable (as Joakim said). But I don't feel strongly about that.

**Comment by etienne-lms** [comment]
We usually prefix the TA uuids and cmd ids:  xtest TAs (TA_<ta-name>_CMD_<cmd>) and pTAs (PTA_<ta-name>_<cmd>.

I preferred an explicit prefix (whatever is is) to recall this is an optee_examples TA.
I could use, for example `TA_SECURE_STORAGE_UUID` for #5 or TA_AES_UUID fpr #3 but I felt they were not very accurate.

**Comment by jforissier** [comment]
@etienne-lms sure, that's fine with me.

**Comment by jbech-linaro** [comment]
Otherwise this might work:
`OPEN_PORTABLE_TRUSTED_EXECUTION_ENVIRONMENT_EXAMPLE_TRUSTED_APPLICATION_ADVANCED_ENCRYPTION_STANDARD_UNIVERSALLY_UNIQUE_IDENTIFIER` 
or why not in Hungerian notation?
`OpenPortableTrustedExecutionEnvironmentExampleTrustedApplicationAdvancedEncryptionStandard_UniversallyUniqueIdentifier`

Autocomplete can handle that too :wink:

**Comment by etienne-lms** [comment]
Latest proposal superseded by #9. Will close if no objection.

**Pull request closed without merging**
