### PR TITLE
simple typo fixes in TA_basics.md

### PR DESCRIPTION
**Pull request by wamserma**
Implementaion -> Implementaton

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Please add a Signed-off-by tag to the commit message.
With that you can also add:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by wamserma** [comment]
added some more fixes

**Comment by jforissier** [comment]
@wamserma please squash the commits and add the requested tags (Signed-off-by: and Reviewed-by:). Otherwise this PR cannot be merged.

**Comment by igoropaniuk** [comment]
Merged

**Pull request merged**
